abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView, TemplateView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('', include('apitokens.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

abuse/models.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.gis.geoip2 import GeoIP2, GeoIP2Exception
from django.core.validators import validate_ipv46_address
from django.db import models
from django.urls import reverse

from extended_choices import Choices
from geoip2.errors import GeoIP2Error

from constants.base import ABUSE_TYPE, ABUSE_TYPE_EXTENSION, ABUSE_TYPE_RATING
from common.model_mixins import CreatedModifiedMixin, TrackChangesMixin
import extensions.fields

User = get_user_model()


class AbuseReport(CreatedModifiedMixin, TrackChangesMixin, models.Model):
    TYPE = ABUSE_TYPE

    REASONS = Choices(
        ('OTHER', 127, 'Other'),
        ('DAMAGE', 1, 'Damages computer and/or data'),
        ('SPAM', 2, 'Creates spam or advertising'),
        ('BROKEN', 3, "Doesn't work, breaks Blender, or slows it down"),
        ('POLICY', 4, 'Hateful, violent, or illegal content'),
        ('DECEPTIVE', 5, "Pretends to be something it's not"),
    )

    STATUSES = Choices(
        ('UNTRIAGED', 1, 'Untriaged'),
        ('DISMISSED', 2, 'Dismissed'),
        ('RESOLVED', 3, 'Resolved'),
    )

    # NULL if the reporter is anonymous.
    # FIXME? make non-null
    reporter = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='abuse_reported',
        on_delete=models.SET_NULL,
    )
    # An abuse report can be for an extension or a user.
    # If user is set then extension should be null.
    # If extension is null then user should be set.
    user = models.ForeignKey(
        User, null=True, related_name='abuse_reports', on_delete=models.CASCADE
    )
    extension = models.ForeignKey(
        'extensions.Extension', blank=True, null=True, on_delete=models.CASCADE
    )
    extension_version = extensions.fields.VersionStringField(max_length=64, null=True, blank=True)
    rating = models.ForeignKey('ratings.Rating', blank=True, null=True, on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    reason = models.PositiveSmallIntegerField(
        default=REASONS.OTHER, choices=REASONS.choices, blank=False, null=False
    )
    version = extensions.fields.VersionStringField(
        max_length=64,
        null=True,
        blank=True,
        help_text=('Version of Blender affected by this report, if applicable.'),
    )
    type = models.PositiveSmallIntegerField(
        default=ABUSE_TYPE_EXTENSION, choices=TYPE.choices, blank=False, null=False
    )

    status = models.PositiveSmallIntegerField(default=STATUSES.UNTRIAGED, choices=STATUSES.choices)
    moderator_note = models.TextField(blank=True, null=True)
    processed_by = models.ForeignKey(
        User,
        null=True,
        related_name='abuse_reports_processed',
        on_delete=models.PROTECT,
    )

    @classmethod
    def lookup_country_code_from_ip(cls, ip):
        try:
            # Early check to avoid initializing GeoIP2 on invalid addresses
            if not ip:
                raise forms.ValidationError('No IP')
            validate_ipv46_address(ip)
            geoip = GeoIP2()
            value = geoip.country_code(ip)
        # Annoyingly, we have to catch both django's GeoIP2Exception (setup
        # issue) and geoip2's GeoIP2Error (lookup issue)
        except (forms.ValidationError, GeoIP2Exception, GeoIP2Error):
            value = ''
        return value

    @property
    def name(self) -> str:
        return self.extension.name if self.extension else self.user

    def __str__(self) -> str:
        return f'Abuse Report for {self.type} {self.name}'

    @classmethod
    def exists(cls, user_id: int, extension_id: int, rating_id: int = None) -> bool:
        if rating_id is None:
            return cls.objects.filter(
                reporter_id=user_id, extension_id=extension_id, type=ABUSE_TYPE_EXTENSION
            ).exists()
        return cls.objects.filter(
            reporter_id=user_id,
            extension_id=extension_id,
            rating_id=rating_id,
            type=ABUSE_TYPE_RATING,
        ).exists()

    def get_absolute_url(self):
        return reverse('abuse:view-report', args=[self.pk])

    def get_admin_url(self):
        return reverse('admin:abuse_abusereport_change', args=[self.pk])

common/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""

    template_name = 'common/error.html'
    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        # TODO: respond as JSON when this is an XHR.
        if request is None or request.method in {'HEAD', 'OPTIONS'}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view
        context = self.get_context_data(**kwargs)
        context['status'] = self.status
        response = self.render_to_response(context)
        response.status_code = self.status
        return response

common/templates/common/components/_button_generic.html
<a class="btn {{ class }}" href="{{ url }}" title="{{ label }}"
  target="{% if external %}_blank{% endif %}"
  rel="{% if external %}noopener noreferrer{% endif %}">
  {% if icon %}
    <i class="{{ icon }}"></i>
  {% endif %}
  <span>{{ label }}</span>
</a>

common/templates/common/components/external_link.html
{% load common %}

<a href="{{ url }}" rel="nofollow" target="_blank" title="{{ title }}">
  {% if show_icon %}<i class="i-link-external"></i>{% endif %}
  {% if not title %}
    {% if show_domain_only %}
    {{ url|domain_from_url }}
    {% elif show_path %}
    {{ url|path_from_url }}
    {% endif %}
  {% else %}
    {% firstof title url %}
  {% endif %}
</a>

common/templates/common/components/field.html
{% load i18n common %}
{% spaceless %}
  {% with type=field.field.widget.input_type classes=classes|default:"" placeholder=placeholder|default:"" %}
    {% with field=field|remove_cols_rows|add_classes:classes|set_placeholder:placeholder %}
    {% with is_markdown=field.name|is_markdown_field %}
    {% with is_markdown_essential=field.name|is_markdown_field_essential %}
      {% autoescape off %}
        {% firstof label field.label as label %}
        {% firstof help_text field.help_text as help_text %}
      {% endautoescape %}

    {% comment %} Checkboxes {% endcomment %}
    {% if type == 'checkbox' %}
      {{ field }}

      {% if not field.is_hidden %}
      <label for="{{ field.id_for_label }}" class="form-check-label">
        {{ label|safe }}
        {% if field.field.required or required %}<span class="form-required-indicator">*</span>{% endif %}
      </label>
      {% endif %}

    {% comment %} All other input types. {% endcomment %}
    {% else %}

      {% if not field.is_hidden %}
        <label for="{{ field.id_for_label }}">
          {{ label|safe }}
          {% if field.field.required or required %}<span class="form-required-indicator">*</span>{% endif %}
        </label>
      {% endif %}

      {% if is_markdown and not field.is_hidden %}
        <div class="hero-tabs hero-tabs-dynamic-theme mb-2">
          <a id="tab-write-{{field.name}}" href="#write-{{field.name}}" class="is-active">{% trans 'Write' %}</a>
          <a id="tab-preview-{{field.name}}" href="#preview-{{field.name}}">{% trans 'Preview' %}</a>
        </div>
        <section id="preview-{{field.name}}" style="display: none;border-bottom: thin solid rgba(255, 255, 255, 0.1);">
          <div id="markdown-preview-{{field.name}}" class="style-rich-text px-3 pt-2 pb-3">{% trans 'Loading...' %}</div>
        </section>
      {% endif %}

      {% if icon %}
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="{{ icon }}"></i></span>
        </div>
        {{ field }}
      </div>
      {% else %}
        <section id="write-{{field.name}}">
          {{ field }}

          {% comment %}
            Field errors must be direct siblings of related fields to be shown by CSS.

            TODO: @web-assets
            Replace Bootstrap deprecated overspecified form selectors error display handling with a markup agnostic solution.
          {% endcomment %}
          {% include "common/components/field_errors.html" %}
        </section>
      {% endif %}
    {% endif %}

    {% if help_text and not field.is_hidden %}
      <div class="form-text">{{ help_text|safe }}</div>
    {% endif %}

    {% include "common/components/field_errors.html" %}

    {% block scripts %}
    {% if is_markdown and not field.is_hidden %}
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          initMarkdownPreview("{{field.name}}", {
            msgLoading: "{% trans 'Loading...' %}",
            msgError: "{% trans 'Error getting preview...' %}",
            msgEmptyState: "{% trans 'Nothing to preview...' %}",
            isEssential: "{{is_markdown_essential}}" === "True",
          })
        })
      </script>
    {% endif %}
    {% endblock scripts %}

  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
{% endspaceless %}

common/templates/common/components/field_errors.html
{% if field.errors %}
  <div class="invalid-feedback">{{ field.errors }}</div>
{% endif %}

common/templates/common/components/nav_item.html
{# TODO: check if template is used and needed #}
<li class="nav-item {% include "common/components/_nav_item_active" %}">
  {% include "common/components/nav_link.html" %}
</li>

common/templates/common/components/nav_link.html
{% if name %}
  <a class="nav-pills-item {% include "common/components/_nav_item_active" %} {% if classes %}{{ classes }}{% endif %}" href="{% url name %}">{{ title }}</a>
{% elif path %}
  <a class="nav-pills-item {% include "common/components/_nav_item_active" %} {% if classes %}{{ classes }}{% endif %}" href="{{ path }}">{{ title }}</a>
{% endif %}

common/templates/common/components/pagination.html
{% load common %}
{% get_proper_elided_page_range page_obj as page_range %}
<nav>
  {% if page_obj.has_other_pages %}
    <ul class="pagination pb-2">
      {% if page_obj.number != 1 %}
      <li class="page-item page-first">
        <a href="?{% query_transform page=1 %}">
          First
        </a>
      </li>
      {% endif %}

      {% if page_obj.has_previous %}
      <li class="page-item page-prev">
        <a href="?{% query_transform page=page_obj.previous_page_number %}">
          <i class="i-chevron-left"></i> Previous
        </a>
      </li>
      {% endif %}

      {% for page_number in page_range %}
        {% if page_number == '…' %}
          <li class="page-item disabled">
            <span class="page-link px-0">...</span>
          </li>
        {% elif page_obj.number == page_number %}
          <li class="page-item page-current active" aria-current="page">
            <a>{{ page_obj.number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a href="?{% query_transform page=page_number %}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item page-next">
        <a href="?{% query_transform page=page_obj.next_page_number %}">
          Next <i class="i-chevron-right"></i>
        </a>
      </li>
      {% endif %}

      {% if page_obj.number != page_obj.paginator.num_pages %}
      <li class="page-item page-last">
        <a href="?{% query_transform page=page_obj.paginator.num_pages %}">
          Last
        </a>
      </li>
      {% endif %}
    </ul>
  {% endif %}

  <div class="mb-2 mb-lg-0 page-item text-center">
    {{ page_obj.paginator.count }} {{ label }}{{ page_obj.paginator.count | pluralize }}
  </div>
</nav>

common/templates/common/components/status.html
{% with label=label|default:object.get_status_display slug=slug|default:object.get_status_display|slugify %}
  <div class="badge badge-status-{{ slug }} {{ classes }}">
    {% if icon %}<i class="i-status-{{ slug }}"></i>{% endif %}
    <span>{{ label }}</span>
  </div>
{% endwith %}