abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView, TemplateView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('', include('apitokens.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

users/urls.py
from django.urls import path, include

from users.mfa_check import logout_mfa_redirect
from users.views.webhooks import user_modified_webhook
import users.views.settings as settings

app_name = 'users'
urlpatterns = [
    path('webhooks/user-modified/', user_modified_webhook, name='webhook-user-modified'),
    path(
        'settings/',
        include(
            [
                path('profile/', settings.ProfileView.as_view(), name='my-profile'),
                path(
                    'profile/save-notification-preferences/',
                    settings.SaveNotificationPreferencesView.as_view(),
                    name='save-notification-preferences',
                ),
                path(
                    'profile/subscribe-notification-emails/',
                    settings.SubscribeNotificationEmailsView.as_view(),
                    name='subscribe-notification-emails',
                ),
                path('delete/', settings.DeleteView.as_view(), name='my-profile-delete'),
            ]
        ),
    ),
    path('logout-before-mfa-setup/', logout_mfa_redirect, name='logout-before-mfa-setup'),
]

common/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""

    template_name = 'common/error.html'
    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        # TODO: respond as JSON when this is an XHR.
        if request is None or request.method in {'HEAD', 'OPTIONS'}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view
        context = self.get_context_data(**kwargs)
        context['status'] = self.status
        response = self.render_to_response(context)
        response.status_code = self.status
        return response

common/templates/common/error.html
{% extends "common/base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-6 mx-auto text-center">
    <div class="box">
      {% if 'MFA required' in exception.args.0 %}
        <h3>Multi-Factor Authentication Required</h3>
        <p>
          This action requires multi-factor authentication. You will be redirected to the MFA setup page at Blender ID.
        </p>
        <a class="btn btn-primary" href="{% url 'users:logout-before-mfa-setup' %}">
          <i class="i-lock"></i>
          Configure MFA
        </a>
      {% else %}
      <h3>
        {{ status }}
        {% if status == 400 %}
          Bad Request
        {% elif status == 401 %}
          Unauthorized
        {% elif status == 403 %}
          Forbidden
        {% elif status == 404 %}
          Page Not Found
        {% elif status == 405 %}
          Method Not Allowed
        {% elif status >= 500 %}
          Server Error
        {% else %}
          Houston, we have a problem.
        {% endif %}
      </h3>
      <p class="m-0">
        {% if status == 400 %}
        {% elif status == 401 %}
          You are not authorized to visit this page.
        {% elif status == 403 %}
          Access denied.
        {% elif status == 404 %}
          The page you requested does not exist.
        {% elif status == 405 %}
        {% elif status >= 500 %}
        {% endif %}
      </p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

common/templates/common/paginator.html
{% load i18n common %}
{% if num_pages > 1 %}
  <ul class="pagination">
    {% if pager.has_previous %}
      <li class="page-item page-first">
        <a href="?page=1">{% trans "First" %}</a>
      </li>

      <li class="page-item page-prev">
        <a href="?page={{ pager.previous_page_number }}" rel="prev"><i class="i-chevron-left"></i><span class="d-md-inline d-none"> {% trans "Prev" %}</span></a>
      </li>
    {% endif %}

    {% for x in pager.page_range %}
      <li class="page-item {{ x|class_selected:pager.number }}">
        <a href="?page={{ x }}">{{ x }}</a>
      </li>
    {% endfor %}

    {% if pager.has_next %}
      <li class="page-item page-next">
        <a href="?page={{ pager.next_page_number }}" rel="next"><span class="d-md-inline d-none">{% trans "Next" %} </span><i class="i-chevron-right"></i></a>
      </li>

      <li class="page-item page-last">
        <a href="?page={{ num_pages }}">{% trans "Last" %}</a>
      </li>
    {% endif %}
  </ul>

  {# TODO: add paginator page count if needed #}
  {% comment %}
    <div class="num-results">
      {% blocktranslate with begin=pager.start_index end=pager.end_index count=count %}
        Results <strong>{{ begin }}</strong>&ndash;<strong>{{ end }}</strong>
        of <strong>{{ count }}</strong>
      {% endblocktranslate %}
    </div>
  {% endcomment %}
{% endif %}